### ISSUE TITLE
Review all English texts and fix typos in "Architecture" section

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-developer-manual#1]
We are not native English speakers and the documentation really needs some external proofreading.
Pages to review are in ["Architecture" folder](https://github.com/freedomotic/fd-developer-manual/tree/master/docs/source/architecture).

If you choose one or more pages please comment.

**Comment by wly5** [comment]
I made the first pull request for one of the documents.

**Comment by mcicolella** [comment]
@wly5 I can't view your pull request.

**Comment by TheRojam** [comment]
Where i can see the docs??

**Comment by mcicolella** [comment]
http://freedomotic-developer-manual.readthedocs.io/

**Comment by oidz1234** [comment]
Hello, I will take a look at these :+1:

**Comment by mcicolella** [comment]
All pages?

**Comment by murphytrueman** [comment]
Hi @mcicolella. Also happy to take a look at these :)

**Comment by mcicolella** [comment]
@murphytrueman I don't know if @oidz1234 is already working on these.

**Comment by oidz1234** [comment]
@murphytrueman I was planning on looking at them when I have some downtime this week. However if you want to do them I do not mind :)

**Comment by mcicolella** [comment]
All pages have been reviewed so I'm closing this issue.
Thanks to all!
