### ISSUE TITLE
Review all English texts and fix typos in "Triggers" file

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-developer-manual#15]
We are not native English speakers and the documentation really needs some external proofreading.
File to review is [trigger.rst](https://github.com/freedomotic/fd-developer-manual/blob/master/docs/source/rules/triggers.rst).

**Comment by chiranjev** [comment]
i am new to open source......how should i notify you if i want you to change something in the file?
how should i get started with it?
