### ISSUE TITLE
Review all English texts and fix typos in "Reactions (aka Automations)" file

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-developer-manual#16]
We are not native English speakers and the documentation really needs some external proofreading.
File to review is [automations.rst](https://github.com/freedomotic/fd-developer-manual/blob/master/docs/source/rules/automations.rst).

**Comment by seancyw** [comment]
I'll grab this :)

**Comment by seancyw** [comment]
PR[#23](https://github.com/freedomotic/fd-developer-manual/pull/23) created for this issue :)
