### ISSUE TITLE
Review all English texts and fix typos in "Things" section 

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-developer-manual#35]
We are not native English speakers and the documentation really needs some external proofreading.
Pages to review are in ["Things" folder](https://github.com/freedomotic/fd-developer-manual/tree/master/docs/source/things).

If you choose one or more pages please comment.

**Comment by Evantm** [comment]
I'll work on this.

**Comment by lalaithan** [comment]
I have done some proofreading of what-is-a-thing.rst #38 and create-new-thing-types.rst #39
