### ISSUE TITLE
Review all English texts and fix typos in "Plugins" section

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-developer-manual#5]
We are not native English speakers and the documentation really needs some external proofreading.
Pages to review are in ["Plugins" folder](https://github.com/freedomotic/fd-developer-manual/tree/master/docs/source/plugins).

If you choose one or more pages please comment.

**Comment by frextrite** [comment]
Can I work on it? The only work to be done is to proof read the documentation, right?

**Comment by mcicolella** [comment]
@frextrite yes. 
Which page do you want to work on?

**Comment by frextrite** [comment]
Most of the pages look fine to me, with just a few edits here and there. I think I could proof read all of the .rst files but I would not like to be too over confident, so in the beginning I would take up the first 3 files `autodiscovering.rst
bind-things-state-to-hardware-data.rst
bind-things-state-to-web-services-data.rst`

**Comment by mcicolella** [comment]
Ok, you can work on these pages.

**Comment by zer0trip** [comment]
I can help out as well if you want to assign me a few pages.

**Comment by MRDJR97** [comment]
I can also help out if you assign me some pages.

**Comment by mcicolella** [comment]
@SeanCodingOnline can you work on the following pages?
create-a-new-plugin.rst
handle-plugin-errors.rst
internationalization.rst
listen-to-events-programmatically.rst
plugin-lifecycle.rst

**Comment by mcicolella** [comment]
@MRDJR97 can you work on the following pages?
plugin-manifest-configuration.rst
plugin-samples.rst
publish-your-plugin.rst
security.rst
what-is-a-plugin.rst

**Comment by frextrite** [comment]
Please update the Assignees section for this issue too :)

**Comment by mcicolella** [comment]
The following pages are assigned to @frextrite 
autodiscovering.rst 
bind-things-state-to-hardware-data.rst
bind-things-state-to-web-services-data.rst

**Comment by zer0trip** [comment]
Sounds good, I will start on those.

**Comment by murphytrueman** [comment]
Hi @mcicolella I'd love to help out if you have any additional pages to be looked at. Thanks :)

**Comment by mcicolella** [comment]
@SeanCodingOnline would you like to work on other pages?
