### ISSUE TITLE
Review all English texts and fix typos in "Getting started" section

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-developer-manual#6]
We are not native English speakers and the documentation really needs some external proofreading.
Pages to review are in ["Getting started"](https://github.com/freedomotic/fd-developer-manual/tree/master/docs/source/getting-started) folder.

If you choose one or more pages please comment.

**Comment by tejas2005** [comment]
What exactly do you want in the Getting Started section.Please be specific.

**Comment by brihijoshi** [comment]
Hi, I'd like to work on this. I am fluent in English. Can you please assign this to me?

**Comment by mcicolella** [comment]
@brihijoshi Ok, thanks.
